Collections: allow bigger sizes for combine and permutate with .repeated
arturo-lang/arturo pull request #1679
Opened 2024-09-12 07:56 UTC by Eloitor

# Description

Collections: allow bigger sizes for `combine` and `permutate` with `.repeated` option.
https://discord.com/channels/765519132186640445/1283495508354011219

## Type of change

- [ ] Code cleanup
- [ ] Unit tests (added or updated unit-tests)
- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] Enhancement (implementation update, or general performance enhancements)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Documentation (documentation-related additions)

2024-09-12 09:54 UTC, Eloitor commented
closes https://github.com/arturo-lang/arturo/issues/1605

2024-09-12 10:23 UTC, drkameleon reviewed
It's obviously looking good! Great job! 😉 🚀 

Would you mind adding a couple of unit-tests too?

The relevant parts would be e.g:
https://github.com/arturo-lang/arturo/blob/master/tests/unittests/lib.collections.art#L1090

Also, pay attention the corresponding `.res` file (which is what is expected and should reflect the new change.) This is the old-style unit-tests, but since they haven't been all migrated, better put it there and we'll transfer it later.

Either way, awesome job! :)

2024-09-12 11:45 UTC, Eloitor commented
Ready for review.

2024-09-12 14:16 UTC, drkameleon requested changes
Everything looking good. Very nice! 🚀 (and the unit-tests are passing fine too)

Another tiny request to make it even better, if you have time: apparently, we have a dedicated file for `combine`-related unit-tests (these are new-style tests). Could you add a couple there too, covering the new cases - if something is missing that is?

👉🏻 https://github.com/arturo-lang/arturo/blob/master/tests/unitt/lib/collections/combine.test.art

And then... I'm merging! 😉

2024-09-13 15:35 UTC, drkameleon approved these changes

2024-09-13 15:40 UTC, drkameleon commented
And... ready to merge! 🚀

2024-09-13 15:40 UTC, merged